"""
Write a function find_difference() that takes two strings as parameters. The second string is generated by shuffling 
the first string and adding one more letter at a random position. Search for and return the added letter.
"""
def find_difference(s1, s2):
    for i in s2:
        if i not in s1:
            return i

#test case
s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))